---
title: "git_01"
author: "Xavier Cruz"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night. 


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

When I see birches bend to left and right  
Across the lines of straighter darker trees,  
I like to think some boy's been swinging them.  
But swinging doesn't bend them down to stay.  
Ice-storms do that. Often you must have seen them

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  
 
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
"It's very rude of him," she said,  
"To come and spoil the fun."  
  
## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

Out of a pellucid brook  
 Pebbles round and smooth I took :  
 Like a jewel, every one  
 Caught a color from the sun, —  
 Ruby red and sapphire blue,  
 Emerald and onyx too,  
 Diamond and amethyst, —  
 Not a precious stone I missed :  
 Gems I held from every land  
 In the hollow of my hand.  
 Workman Water these had made ;  
 Patiently through sun and shade,  
 With the ripples of the rill  
 He had polished them until,  
 Smooth, symmetrical and bright,  
 Each one sparkling in the light  
 Showed within its burning heart  
 All the lapidary’s art ;  
 And the brook seemed thus to sing :  
 Patience conquers everything !  
 